Feature: Network Assistance and Dynamic Policies
5G-MAG/rt-5gms-application-function pull request #108
Opened 2023-12-12 17:30 UTC by davidjwbbc

# Overview

These changes introduce the Network Assistance and the Dynamic Polices features to the AF as well as including a uplift to the TS26.512 v17.6.0 version specification.

# Network Assistance

The Network Assistance feature has been added but will contains the delivery boost option, the throughput estimation is still under development.

## Activating

The Network Assistance feature can be activated by setting both the `msaf.open5gsIntegration` and `msaf.offerNetworkAssistance` settings in the `msaf.yaml` configuration file to `true`.

## Delivery Boost

This will apply a fixed guaranteed minimum downlink bitrate for a fixed amount of time.

The bitrate to guarantee defaults to "1 Mbps" but can be overridden by setting the `msaf.networkAssistance.deliveryBoost.minDlBitRate` parameter in the `msaf.yaml` configuration file.

The period of time for which the boost is applied defaults to 30 seconds and can be set by setting the number of seconds in the `msaf.networkAssistance.deliveryBoost.boostPeriod` parameter in the `msaf.yaml` configuration file.

# Dynamic Policies

Dynamic Policies will be advertised in the Service Access Information when Policy Templates are configured for the provisioning session using the API at reference point M1.

In this implementation Policy Templates immediately transition into the __Ready__ state as soon as they are defined. This behaviour will remain until a suitable API is introduced to allow network operators to query and approve/deny policy templates.

# Other changes
- The `Configuration` class has been moved out of the m1-session tool and into the rt_m1_client module so that it can be easily shared between the python applications (currently used by the m1-session and msaf-configuration tools).
- The Open5GS OpenAPI templates have been replaced for the AF specific object models with versions which will honour read-only attributes and min/max values for integer ranges and will also return a reason for serialisation errors.
  - This introduces function calls for convertRequestToJSON(), convertResponseToJSON(), parseRequestFromJSON() and parseResponseFromJSON() to process or ignore properties marked as read-only in the relevant situations.
  - All 5GMS AF specific models are now prefixed with `msaf_api_` to distinguish them from the Open5GS OpenAPI models.

2023-12-12 17:42 UTC, rjb1000 requested changes
Found a few missing author names, and a few cases where the copyright year on new files was 2022 instead of 2023.

In addition, any files started in 2022 but touched in 2023 should have "2022-2023" as their copyright year.

2023-12-12 17:42 UTC, rjb1000 commented on src/5gmsaf/dynamic-policy.h
> +Copyright: (C) 2022 British Broadcasting Corporation
2023

2023-12-12 17:42 UTC, rjb1000 commented on src/5gmsaf/local.h
> +Copyright: (C) 2022 British Broadcasting Corporation
2023

2023-12-12 17:42 UTC, rjb1000 commented on src/5gmsaf/network-assistance-delivery-boost.c
> +Copyright: (C) 2022 British Broadcasting Corporation
2023

2023-12-12 17:42 UTC, rjb1000 commented on src/5gmsaf/network-assistance-delivery-boost.h
> +Copyright: (C) 2022 British Broadcasting Corporation
2023

2023-12-12 17:42 UTC, rjb1000 commented on src/5gmsaf/network-assistance-session.h
> +Copyright: (C) 2022 British Broadcasting Corporation
2023

2023-12-12 17:42 UTC, rjb1000 commented on src/5gmsaf/openapi-templates/model-header.mustache
Shouldn't this file have a copyright statement added?

2023-12-12 17:42 UTC, rjb1000 commented on src/5gmsaf/pcf-session.c
> +Copyright: (C) 2022 British Broadcasting Corporation
2023

2023-12-12 17:42 UTC, rjb1000 commented on src/5gmsaf/pcf-session.c
Missing author name.

2023-12-12 17:42 UTC, rjb1000 commented on src/5gmsaf/pcf-session.h
> +Copyright: (C) 2022 British Broadcasting Corporation
2023

2023-12-12 17:42 UTC, rjb1000 commented on src/5gmsaf/policy-template.h
> +Copyright: (C) 2022 British Broadcasting Corporation
2023

2023-12-12 17:42 UTC, rjb1000 commented on src/5gmsaf/timer.c
Why isn't this file included by reference from the Open5GS project?

2023-12-12 17:42 UTC, rjb1000 commented on src/5gmsaf/timer.h
> +Copyright: (C) 2022 British Broadcasting Corporation
2023

2023-12-12 17:42 UTC, rjb1000 commented on tests/msaf/pcf-cache-test.h
Missing author name.

2023-12-12 17:42 UTC, rjb1000 commented on src/5gmsaf/network-assistance-delivery-boost.h
> +Copyright: (C) 2022 British Broadcasting Corporation
Also missing author name.

2023-12-12 17:43 UTC, rjb1000 commented on src/5gmsaf/network-assistance-delivery-boost.c
> +Copyright: (C) 2022 British Broadcasting Corporation
Also missing author name.

2023-12-12 17:43 UTC, rjb1000 commented on src/5gmsaf/local.h
> +Copyright: (C) 2022 British Broadcasting Corporation
Also missing author name.

2023-12-12 17:43 UTC, rjb1000 commented on src/5gmsaf/policy-template.h
> +Copyright: (C) 2022 British Broadcasting Corporation
Also missing author name.

2023-12-12 17:43 UTC, rjb1000 commented on src/5gmsaf/timer.h
> +Copyright: (C) 2022 British Broadcasting Corporation
Also missing author name.

2023-12-13 10:37 UTC, davidjwbbc commented on src/5gmsaf/timer.c
Each NF has it's own timer.c file. It's there to handle our local 5GMS AF timers.

2023-12-13 15:00 UTC, davidjwbbc commented on tests/msaf/pcf-cache-test.h
done

2023-12-13 15:00 UTC, davidjwbbc commented on src/5gmsaf/timer.h
> +Copyright: (C) 2022 British Broadcasting Corporation
done

2023-12-13 15:01 UTC, davidjwbbc commented on src/5gmsaf/timer.c
I've modified the header to show that it originates from Open5GS but with changes we've added to handle 5GMS AF timer events.

2023-12-13 15:01 UTC, davidjwbbc commented on src/5gmsaf/policy-template.h
> +Copyright: (C) 2022 British Broadcasting Corporation
done

2023-12-13 15:02 UTC, davidjwbbc commented on src/5gmsaf/pcf-session.h
> +Copyright: (C) 2022 British Broadcasting Corporation
done

2023-12-13 15:07 UTC, rjb1000 approved these changes
Thanks for the changes, @davidjwbbc.

2023-12-13 15:11 UTC, merged