M1 | Metrics Reporting Provisioning
5G-MAG/rt-5gms-application-function pull request #137
Opened 2024-03-04 13:52 UTC by stojkovicv

This PR adds CRUD operations for **Metrics Reporting Provisioning API** according to 3GPP TS 26.512 V17.7.0.

Related discussion: https://github.com/5G-MAG/rt-5gms-application-function/issues/68

2024-03-05 12:37 UTC, davidjwbbc requested changes
There are some comments to address.

2024-03-05 12:37 UTC, davidjwbbc commented on src/5gmsaf/msaf-m1-sm.c
> +                                if (msaf_provisioning_session) {
This is not needed as msaf_provisioning_session has already been set and checked earlier... looks like there's a regression on some of the code, on the current development branch, in this area (the whole GET processing) and the other api types (provisioning session, certificates, etc.) shouldn't have this duplicate code either. I'll raise an issue to fix this. But for this PR you can drop these lines and the later 404 provisioning session not found response as it's already been handled elsewhere.

2024-03-05 12:37 UTC, davidjwbbc commented on src/5gmsaf/msaf-m1-sm.c
> +                                        cJSON *mrc_json_data = msaf_api_metrics_reporting_configuration_convertToJSON(metricsReportingConfiguration->config, NULL);
Use `msaf_api_metrics_reporting_configuration_convertResponseToJSON(metricsReportingConfiguration->config)` instead. The `NULL` was wrong anyway.

2024-03-05 12:37 UTC, davidjwbbc commented on src/5gmsaf/msaf-m1-sm.c
> +                                                                                  NULL,
This parameter should be the etag has value, not `NULL`.

2024-03-05 12:37 UTC, davidjwbbc commented on src/5gmsaf/msaf-m1-sm.c
>                                      ogs_free(err);
This can go, as detailed above. (removal of the duplicate lookup of provisioning session and the `if (msaf_provisioning_session) {`)

2024-03-05 12:37 UTC, davidjwbbc commented on src/5gmsaf/msaf-m1-sm.c
> +                                    provisioning_session = msaf_provisioning_session_find_by_provisioningSessionId(message->h.resource.component[1]);
Provisioning session already available in `msaf_provisioning_session` at this point in the code. This duplicate lookup is not needed.

2024-03-05 12:37 UTC, davidjwbbc commented on src/5gmsaf/msaf-m1-sm.c
> +                                        msaf_api_metrics_reporting_configuration_t *updated_config = msaf_api_metrics_reporting_configuration_parseFromJSON(json, false, &parse_err);
Use `msaf_api_metrics_reporting_configuration_parseRequestFromJSON(json, &parse_err)` instead.

2024-03-05 12:37 UTC, davidjwbbc commented on src/5gmsaf/msaf-m1-sm.c
Your code editor appears to have reindented and rewrapped a lot of line in this file making it difficult to see the actual code modifications you've made. In some cases your editor has gotten the indentation wrong and this needs correcting.

2024-03-05 12:37 UTC, davidjwbbc commented on src/5gmsaf/msaf-m1-sm.c
> +
You should look up the metrics reporting configuration in the `msaf_provisioning_session` here and 404 if it doesn't exist. Then later on for the update you can pass the `msaf_metrics_reporting_configuration_t*` and the new OpenAPI model to perform the update.

2024-03-05 12:37 UTC, davidjwbbc commented on src/5gmsaf/msaf-m1-sm.c
> +                                    } else{
fix indent

2024-03-05 12:37 UTC, davidjwbbc commented on src/5gmsaf/msaf-m1-sm.c
> +                                            int result = update_metrics_configuration(msaf_provisioning_session, metrics_reporting_configuration_id, updated_config);
Before this remember to set the metrics reporting configuration id in `updated_config` as its read-only and therefore won't be parsed by the `...parseRequestFromJSON()` function.

If you've already looked up the existing config above (to do a 404 error if it doesn't exist) then this function call can just take the existing config object (i.e. object containing OpenAPI config, etag, receivedTime) and the new OpenAPI config object. There should be no need to pass the provisioning session as the map will not be updated, just the value it's pointing to.

2024-03-05 12:37 UTC, davidjwbbc commented on src/5gmsaf/msaf-m1-sm.c
> +                                    }
Not needed, as stated above.

2024-03-05 12:37 UTC, davidjwbbc commented on src/5gmsaf/msaf-m1-sm.c
> +                                    if (provisioning_session) {
Should already be handled elsewhere, not needed here, just use `provisioning_session`.

2024-03-05 12:37 UTC, davidjwbbc commented on src/5gmsaf/msaf-m1-sm.c
I don't see any handling of OPTIONS responses for the metrics reporting provisioning.

2024-03-06 16:02 UTC, davidjwbbc requested changes
Almost there, just some indents in the SWITCH...CASE...END blocks to put back, a couple of redundant provisioning session lookups to remove and the OPTIONS responses to implement.

Everything else looks great.

2024-03-06 16:22 UTC, davidjwbbc commented on src/5gmsaf/msaf-m1-sm.c
> +                                                int result = update_metrics_configuration(metrics_configuration, updated_config);
You'll need to add the following before the call to `update_metrics_configuration()` or make it part of the update function (i.e. copy the old readOnly value(s) from the exiting configuration to the new one on update):
```c
updated_config->metrics_reporting_configuration_id = msaf_strdup(metrics_reporting_configuration_id);
```
The id will not have been parsed from the update request, even if it's present in the request object, as it's marked as `readOnly` in the TS26512_M1_MetricsReportingProvisioning.yaml overrides YAML file. This causes the field to be ignored by the parsing routine when dealing with a request JSON body.

2024-03-07 12:09 UTC, stojkovicv commented
@davidjwbbc Please let me know if you can spot any of false indentations with the latest commit. Appears in my IDE that there are no more such lines.

2024-03-07 12:38 UTC, davidjwbbc requested changes

2024-03-07 12:38 UTC, davidjwbbc commented on src/5gmsaf/msaf-m1-sm.c
> +                                            ogs_assert(true == ogs_sbi_server_send_response(stream, response));
This needs splitting for OPTIONS for `.../{provisioning_session_id}/metrics-reporting-configurations` and  `.../{provisioning_session_id}/metrics-reporting-configurations/{metrics-reporting-configuration-id}`... see the certificates OPTIONS for guidance (lines 1729-1755).

2024-03-07 12:38 UTC, davidjwbbc commented on src/5gmsaf/msaf-m1-sm.c
> +                            break;
This still needs fixing

2024-03-07 12:38 UTC, davidjwbbc commented on src/5gmsaf/msaf-m1-sm.c
> +                            break;
The indents here still need fixing

2024-03-07 12:38 UTC, davidjwbbc commented on src/5gmsaf/msaf-m1-sm.c
OPTIONS need splitting for different paths, see guidance comment on the Options code.

2024-03-07 13:24 UTC, stojkovicv commented on src/5gmsaf/msaf-m1-sm.c
> +                            break;
I don't understand why this space persist, as it's been correctly alligned in my editor.

2024-03-07 13:24 UTC, stojkovicv commented on src/5gmsaf/msaf-m1-sm.c
> +                            break;
This is also correct in my IDE

2024-03-07 15:24 UTC, davidjwbbc commented on src/5gmsaf/msaf-m1-sm.c
> +                            break;
Check you've not added tab (^I or char 0x09) instead of space characters. That's the usual reason for indents appearing incorrectly.

2024-03-07 15:29 UTC, davidjwbbc approved these changes

2024-03-07 16:11 UTC, davidjwbbc commented
PR has been merged on the command line (with whitespace fixes), but GitHub not recognising it. Going to close this PR which will mark it as not merged, but really it is!

2024-03-07 16:11 UTC, closed without merging