M5 | Metrics Reporting API
5G-MAG/rt-5gms-application-function pull request #143
Opened 2024-03-14 12:27 UTC by stojkovicv

## Description
This merge request expands Application Function with a _Create_ operation at interface M5. This is the only operation defined in _TS26.512 (v17.7)_ for reporting QoS metrics.

## Changes

- Bash generator now pulls declarations for M5 Metrics API.

- Service Access Information module has been expanded to iterate through map of Metrics Reporting objects, and to populate JSON subarray `clientMetricsReportingConfiguration`. This array contains, previously, provisioned Metrics Reporting data.

- M5 state machine now contains code to handle Metrics Reporting `POST` request. It expects XML data as a payload, parses relevant information from it, so that metrics data can be written locally with a correct parameters in the file name (https://github.com/5G-MAG/rt-5gms-application-function/issues/90). There is a logical checking that enables M5 _Create_ operation only if, at least one, Metrics Configuration has been previously provisioned.

- Finally, Service Access Information cache clearance has been added for M1 _Create_, _Update_ and _Delete_ operations, because they affect SAI content. This will enable to correctly populate Service Access Information list along with a `clientMetricsReportingConfiguration`.

2024-03-14 12:39 UTC, rjb1000 commented
Note that although the HTTP `POST` method is used to submit a QoE metrics report to the 5GMS AF at reference point M5, it isn't correct to refer to this as a _Create_ operation. It's not creating a resource on the 5GMS AF in the RESTful sense. You can't subsequently retrieve the resource using `GET`, for example.

It's more accurate to think of this operation in terms of the Remote Procedure Call metaphor: you provide the metrics report to the 5GMS AF at the RPC interface and get a return code in response. And that's the end of the matter.

2024-03-14 16:32 UTC, davidjwbbc requested changes

2024-03-14 16:32 UTC, davidjwbbc commented on src/5gmsaf/service-access-information.c
> +
The normal rule with SAI is that an entry is omitted if it's empty. Initialising the list here means that the list will always be included even if it's empty.

`cmrc_list` should just be initialised to `NULL` here and the `OpenAPI_list_create()` (and `ogs_assert()`) only called if the list will not be empty (see below).

2024-03-15 11:05 UTC, stojkovicv commented
@davidjwbbc Is HTTP `Options` method supposed to be added for the Metics M5 endpoint? It exist for Consumption Reporting...

2024-03-15 12:42 UTC, davidjwbbc approved these changes

2024-03-15 15:12 UTC, davidjwbbc requested changes
Changing Approval to request to add OPTIONS response for the relevant path.

2024-03-18 12:24 UTC, stojkovicv commented on src/5gmsaf/msaf-m5-sm.c
> +                            ogs_assert(true == nf_server_send_error(stream, OGS_SBI_HTTP_STATUS_NOT_FOUND, 0, message, "No Metrics ID Found", NULL, NULL, m5_metricsreporting_api, app_meta));
@davidjwbbc I tought that it might be a good improvment to precise the error here, please let me know if it should be revoked to original title

2024-03-18 18:22 UTC, davidjwbbc approved these changes

2024-03-18 18:22 UTC, davidjwbbc commented on src/5gmsaf/msaf-m5-sm.c
> +                            ogs_assert(true == nf_server_send_error(stream, OGS_SBI_HTTP_STATUS_NOT_FOUND, 0, message, "No Metrics ID Found", NULL, NULL, m5_metricsreporting_api, app_meta));
That's the text that ends up in the title in the ProblemDetails, so I don't see a problem with being a bit more precise.

2024-03-18 18:25 UTC, merged