Documentation updates
5G-MAG/rt-5gms-application-function pull request #161
Opened 2024-04-28 13:40 UTC by jordijoangimenez

2024-04-30 08:55 UTC, dsilhavy commented on README.md
> +If you wish to test 5GMSd Application Function v1.1.x then please see the [Testing the M3 Interface on v1.1.0](https://5g-mag.github.io/Getting-Started/pages/5g-media-streaming/rt-5gms-application-fu
Broken link, needs to be added to getting started

2024-04-30 08:55 UTC, dsilhavy commented on README.md
> +For versions after v1.1.x (i.e. v1.2.0 and above) please use the [Testing the M3 Interface on v1.2.0](https://5g-mag.github.io/Getting-Started/pages/5g-media-streaming/rt-5gms-application-function/te
Broken link, needs to be added to getting started

2024-04-30 08:55 UTC, dsilhavy commented on README.md
> +If you are testing versions up to v1.1.x then please visit the [Testing: M5 Interface on v1.0.0](https://5g-mag.github.io/Getting-Started/pages/5g-media-streaming/rt-5gms-application-function/testing
Broken link, needs to be added to getting started

2024-04-30 08:55 UTC, dsilhavy commented on README.md
> +[Testing the M5 Interface on v1.2.0](https://5g-mag.github.io/Getting-Started/pages/5g-media-streaming/rt-5gms-application-function/testing-m5-v120.html) page.
Broken link, needs to be added to getting started

2024-04-30 08:55 UTC, dsilhavy commented on README.md
> +[Testing the M5 Interface on v1.3.0](https://5g-mag.github.io/Getting-Started/pages/5g-media-streaming/rt-5gms-application-function/testing-m5-v130.html) page.
Broken link, needs to be added to getting started

2024-04-30 08:55 UTC, dsilhavy commented on README.md
> +For detailed instructions on how to use the Postman Collection please refer to this [documentation](https://5g-mag.github.io/Getting-Started/pages/5g-media-streaming/rt-5gms-application-function/test
Broken link, needs to be added to getting started

2024-05-02 09:13 UTC, dsilhavy commented
@jordijoangimenez Can you please fix the broken links now that we merged https://github.com/5G-MAG/Getting-Started/pull/65

2024-05-02 11:01 UTC, dsilhavy requested changes

2024-05-02 18:07 UTC, jordijoangimenez reviewed
All fixed

2024-05-03 06:51 UTC, dsilhavy approved these changes

2024-05-03 06:51 UTC, merged