Reflect the enabled state of PolicyTemplate provisioning in the OPTIONS method
5G-MAG/rt-5gms-application-function pull request #162
Opened 2024-07-12 15:26 UTC by davidjwbbc

Fixes 5G-MAG/rt-5gms-application-provider#45

If the `open5gsIntegration` YAML configuration file variable is not true then this removes the `Allow: POST` response header from the headers returned for the `OPTIONS` method on the `.../provisioning-sessions/{provisioningSessionId}/policy-templates` M1 API path. This allows the UI to detect if provisioning of PolicyTemplates will be allowed or not.

2024-07-12 15:37 UTC, stojkovicv approved these changes

2024-07-12 16:01 UTC, rjb1000 commented on src/5gmsaf/msaf-m1-sm.c
> +                                                    response = nf_server_new_response(request->h.uri, NULL,  0, NULL, 0, disabled_methods, m1_policytemplatesprovisioning_api, app_meta);
Hopefully `disabled_methods` is the set of methods when the 5G Core integration is disabled, not the set of disabled methods as its name implies.

Could we improve the variable name to be more intention-revealing? How about `methods_core-integration-disabled` or something like that?

2024-07-12 16:02 UTC, rjb1000 requested changes
Broadly fine, @davidjwbbc. Just suggested a slight change of name.

2024-07-16 04:50 UTC, davidjwbbc commented on src/5gmsaf/msaf-m1-sm.c
> +                                                    response = nf_server_new_response(request->h.uri, NULL,  0, NULL, 0, disabled_methods, m1_policytemplatesprovisioning_api, app_meta);
changed the name to `methods_feature_disabled` and also renamed the other local static string `methods` to `methods_feature_enabled`

2024-07-16 04:51 UTC, merged