Metrics Reporting Provisioning API at reference point M1
5G-MAG/rt-5gms-application-function pull request #86
Opened 2023-09-01 09:32 UTC by stojkovicv

Implemented entire scope of operations (CRUD) for Metrics Reporting Provisioning API according to 3GPP TS 26.512 V17.5.0. All operations are successfully tested using mocked JSON data.

Related discussion: #68

2023-09-01 17:12 UTC, davidjwbbc requested changes
Can you please rebase your commits onto the development branch

2023-09-04 09:41 UTC, stojkovicv commented
@davidjwbbc I revoked minor changes from `server.c` and Python framework with latest commit.
In order to rebase commits to the development branch:
- I've setted official AF repository as "upstream" branch to my local forked one
- Fetched all the changes
- Checkout to `development`
and when I `git merge upstream/development`, the message says `Already up to date.`
What am I missing there?

2023-09-04 10:18 UTC, davidjwbbc commented on src/5gmsaf/msaf-m1-sm.c
> +<<<<<<< HEAD
These conflicts need to be resolved, not committed. You need to assess the code changes between `<<<<<<< HEAD` and `=======`, and `=======` and `>>>>>>> upstream/development`, and then try to merge the two by hand. Sometimes this may mean just leaving one set and deleting the other, or you may have to merge bits of both sets of changes together.

2023-09-04 10:27 UTC, stojkovicv commented on src/5gmsaf/msaf-m1-sm.c
> +<<<<<<< HEAD
Thanks for the explanation. I wasn't sure what is the reason for conflict, so I used `git checkout --theirs ` command to keep the version from `development` branch within the files that doesn't really need to be changed, for example: `git checkout --theirs tools/python3/lib/rt_m1_client/session.py`
That solved the conflicts, then I just pushed rebased version.

2023-09-04 11:01 UTC, davidjwbbc requested changes
You appear to have backed out several code improvements and bug fixes. Please fix your rebase to leave these changes in.

2023-09-04 11:07 UTC, stojkovicv commented
Could you please be more precise on that? Which files are affected?

2023-09-04 11:29 UTC, davidjwbbc commented on src/5gmsaf/application-server-context.c
> +msaf_application_server_add(char *canonical_hostname, char *url_path_prefix_format, int m3_port)
Several changes in this file remove the ability to specify that the AF should use a different M3 host name than the canonical name advertised in the CHC response to the AP.

2023-09-04 11:34 UTC, davidjwbbc commented on src/5gmsaf/msaf-m1-sm.c
> +    char *nf_name = ogs_msprintf("5GMSdAF-%s", msaf_self()->server_name);
Another reverted improvement here

2023-09-04 11:34 UTC, davidjwbbc commented on src/5gmsaf/meson.build
> +libsbi_dep = open5gs_project.get_variable('libsbi_dep')
Changes to this file remove a build improvement to allow an HTTP 1.1 server library and HTTP 2.0 server library to co-exist and also improvements to how the OpenAPI files are retrieved and processed.

2023-09-04 11:37 UTC, davidjwbbc commented on src/5gmsaf/msaf-m1-sm.c
> +            SWITCH(message->h.method)
Your code editor has lost indentation here. If you use automatic reindenting around any of the `SWITCH` or `CASE` statements in the code then you will have to go back an manually fix the indenting (code editors don't indent the `SWITCH`, `CASE` and subsequent lines properly.

2023-09-04 11:40 UTC, davidjwbbc commented on src/5gmsaf/msaf-m1-sm.c
This whole file is a mess of white space changes due to automatic re-indenting that has gone wrong. It makes it very difficult to see what you've changed and if you've reverted things here.

2023-09-04 11:41 UTC, davidjwbbc commented on src/5gmsaf/msaf-sm.c
> +    char *nf_name = ogs_msprintf("5GMSdAF-%s", msaf_self()->server_name);
Another reverted change here.

2023-09-04 11:42 UTC, davidjwbbc commented on src/5gmsaf/msaf-sm.c
Again poor re-indenting has meant that a lot of white space changes have been committed here making it very difficult to pick out your changes.

2023-09-04 11:44 UTC, davidjwbbc commented on src/5gmsaf/provisioning-session.c
> +    OpenAPI_list_t *media_entry_point_list;
regression here too.

2023-09-04 11:44 UTC, davidjwbbc commented on src/5gmsaf/provisioning-session.c
> +        ogs_error("Unable to retrieve Provisioning Session [%s]", provisioning_session_id);
Regression here too

2023-09-04 11:48 UTC, davidjwbbc commented on subprojects/open5gs
I don't think your changes should be pulling in changes to the open5gs subproject.

2023-09-04 11:49 UTC, davidjwbbc commented on subprojects/rt-common-shared
Again you shouldn't be touching the commit version of the subproject. This looks like another reverted change.

2023-09-04 11:51 UTC, davidjwbbc commented on tools/python3/lib/rt_m1_client/client.py
> +    async def createOrReserveServerCertificate(self, provisioning_session_id: ResourceId, csr=False) -> Optional[ServerCertificateSigningRequestResponse]:
Another regression here.

2023-09-04 11:51 UTC, davidjwbbc commented on tools/python3/lib/rt_m1_client/client.py
> +from typing import Optional, Union, Tuple, Dict, Any, TypedDict
Regression here.

2023-09-04 11:51 UTC, davidjwbbc commented on tools/python3/lib/rt_m1_client/client.py
> +        of the newly reserved certificate.
Regression here too.

2023-09-04 11:52 UTC, davidjwbbc commented on tools/python3/lib/rt_m1_client/client.py
Changes here have backed out important certificate handling improvemnets.

2023-09-04 11:53 UTC, davidjwbbc commented on tools/python3/lib/rt_m1_client/session.py
Again, regression to the certificate handling.

2023-09-04 13:40 UTC, davidjwbbc commented on subprojects/open5gs
Please remove this commit change to the open5gs submodule as it is a regression.

2023-09-04 13:41 UTC, davidjwbbc commented on subprojects/rt-common-shared
Please remove this commit change to the rt-common-shared submodule as it is a regression.

2023-09-04 13:42 UTC, davidjwbbc commented on tools/python3/lib/rt_m1_client/session.py
This is a whitespace only change, please remove it from this pull request.

2023-09-04 13:42 UTC, davidjwbbc commented on tools/python3/lib/rt_m1_client/client.py
This is a whitespace only change, please remove it from this pull request.

2023-09-04 13:52 UTC, davidjwbbc requested changes

2023-09-04 13:52 UTC, davidjwbbc commented on src/5gmsaf/server.c
This is a whitespace only change, please remove it from this pull request.

2023-09-04 13:52 UTC, davidjwbbc commented on src/5gmsaf/provisioning-session.h
> +#include "openapi/model/metrics_reporting_configuration.h"
Regression: #includes added by another commit have been removed.

2023-09-04 13:52 UTC, davidjwbbc commented on src/5gmsaf/meson.build
This is a whitespace only change, please remove it from this pull request.

2023-09-04 13:52 UTC, davidjwbbc commented on src/5gmsaf/application-server-context.h
This is a whitespace only change, please remove it from this pull request.

2023-09-04 13:52 UTC, davidjwbbc commented on src/5gmsaf/application-server-context.c
This is a whitespace only change, please remove it from this pull request.

2023-09-04 15:21 UTC, stojkovicv commented
Changes done within M1 session tool and other files (like `server.c`) are done before - with some of the first commits, when there was an effort to enable MRC by using tool. Since that variant is not implemented with this pull request, and all the changes naturally stayed in the git history, I am considering an option of opening brand new pull request, tidying up all the changes - essentially removing all unnecessary ones from this PR. I also can not see the review of `subprojects/open5gs`, in order to fix it, and I'm still not sure how and why those files have been affected.
Is there more reasonable approach of removing unnecessary changes from PR?

2023-09-05 12:32 UTC, dsilhavy commented
We agreed to provide a new pull request based on `origin/development` including only the relevant changes. Closing this for now.

2023-09-05 12:32 UTC, closed without merging