Metrics Reporting Provisioning API at reference point M1
5G-MAG/rt-5gms-application-function pull request #87
Opened 2023-09-05 19:37 UTC by stojkovicv

Implemented entire scope of operations (CRUD) for **Metrics Reporting Provisioning API** according to 3GPP TS 26.512 V17.5.0. All operations are successfully tested using mocked JSON data.

Related discussion: #68

2023-09-06 10:32 UTC, davidjwbbc requested changes
I've marked some inline changes and improvements.

You also need to add `metrics-reporting-provisioning.c` and `metrics-reporting-provisioning.h` to the sources list in `src/5gms/meson.build`.

2023-09-06 10:32 UTC, davidjwbbc commented on src/5gmsaf/metrics-reporting-provisioning.c
> +#include "openapi/model/metrics_reporting_configuration.c"
You shouldn't be including .c files, only .h files.

This can lead to functions being defined twice in the final compile.

2023-09-06 10:32 UTC, davidjwbbc commented on src/5gmsaf/metrics-reporting-provisioning.h
> +static char *calculate_metrics_reporting_configuration_hash(OpenAPI_metrics_reporting_configuration_t *metricsReportingConfiguration);
You should not declare static functions in a .h file, this function prototype belongs near the top of the .c file that implements this function.

2023-09-06 10:32 UTC, davidjwbbc commented on src/5gmsaf/provisioning-session.c
> +        }
You are adding the metrics reporting objects to the output here, but the specification only requires a list of the ids.

This should probably be:
```c
provisioning_session->metrics_reporting_configuration_ids = (OpenAPI_set_t*)OpenAPI_list_create();
for (metrics_node=ogs_hash_first(msaf_provisioning_session->metricsReportingMap); metrics_node; metrics_node = ogs_hash_next(metrics_node)) {
    OpenAPI_list_add(provisioning_session->metrics_reporting_configuration_ids, (const char *)ogs_hash_this_key(metrics_node);
}
```

2023-09-06 10:32 UTC, davidjwbbc commented on src/5gmsaf/provisioning-session.h
> +    char *metricsReportingConfigurationId;
The metrics reporting configurations are all held in the map below, this single id should therefore never be used and can be removed.

2023-09-06 10:32 UTC, davidjwbbc commented on src/5gmsaf/provisioning-session.h
> +    char *metricsReportingConfigurationHash;
These single configuration, time received and hash should be held in the map above and are therefore never used here and can be removed.

2023-09-06 10:32 UTC, davidjwbbc commented on src/5gmsaf/msaf-m1-sm.c
> +#include "metrics-reporting-provisioning.c"
Don't #include a .c file, only #include the .h file.

2023-09-06 10:32 UTC, davidjwbbc commented on src/5gmsaf/msaf-m1-sm.c
> +                                    if (msaf_provisioning_session) {
This will always be true as it's already been checked by the if at line 964, it's redundant here.

2023-09-06 13:40 UTC, stojkovicv commented on src/5gmsaf/msaf-m1-sm.c
> +#include "metrics-reporting-provisioning.c"
Yes, but compiler is returning very persistent errors when I include `metrics-reporting-provisioning.h` instead. Not sure if relevant - but there is no related header file for `msaf-m1-sm.c`

2023-09-06 13:46 UTC, stojkovicv commented on src/5gmsaf/msaf-m1-sm.c
> +                                    if (msaf_provisioning_session) {
Fixed with the latest commit.

2023-09-06 13:46 UTC, stojkovicv commented on src/5gmsaf/msaf-m1-sm.c
> +                                    msaf_provisioning_session = msaf_provisioning_session_find_by_provisioningSessionId(message ->h.resource.component[1]);
Fixed with the latest commit.

2023-09-06 13:46 UTC, stojkovicv commented on src/5gmsaf/provisioning-session.h
> +    char *metricsReportingConfigurationId;
Excluded with latest commit.

2023-09-06 13:46 UTC, stojkovicv commented on src/5gmsaf/provisioning-session.c
> +        }
Fixed with the latest commit.

2023-09-06 13:51 UTC, stojkovicv commented
Including metrics related files within `src/5gms/meson.build` affects two metrics functions in terms of returning `int` from pointer's action:
```
invalid type argument of ‘->’ (have ‘int’)
  129 |     for (provisioning_node = ogs_hash_first(msaf_self()->provisioningSessions_map); 
```
Not sure what is the reason for that.

2023-09-06 14:07 UTC, davidjwbbc commented
> Including metrics related files within `src/5gms/meson.build` affects two metrics functions in terms of returning `int` from pointer's action:
> 
> ```
> invalid type argument of ‘->’ (have ‘int’)
>   129 |     for (provisioning_node = ogs_hash_first(msaf_self()->provisioningSessions_map); 
> ```
> 
> Not sure what is the reason for that.

It looks like msaf_self() isn't being defined and is using the compiler default `int` return. Try adding `#include "context.h"` to the top of `src/5gmsaf/metrics-reporting-provisioning.c`.

2023-09-06 14:14 UTC, davidjwbbc commented on src/5gmsaf/msaf-m1-sm.c
> +#include "metrics-reporting-provisioning.c"
At the moment `src/5gmsaf/msaf-sm.h` is acting as a combined .h file for `msaf-sm.c`, `msaf-m1-sm.c`, `msaf-m5-sm.c` and `msaf-mgmt-sm.c`. It should really be split out into separate files at some point, but is fine how it is for now.

Shall we run through the errors over slack and I can help you resolve them. It's probably just a missing `#include` or two somewhere.

2023-09-06 17:06 UTC, davidjwbbc requested changes
Just a couple of last small things to tidy up and I think this is good to go. We'll just await Daniel's approval too before merging.

2023-09-06 17:06 UTC, davidjwbbc commented on src/5gmsaf/provisioning-session.c
> +        OpenAPI_list_free(provisioning_session->server_certificate_ids);
I think there needs to be an `OpenAPI_list_free(provisioning_session->metrics_reporting_configuration_ids)` added here to avoid memory leaks.

2023-09-07 14:38 UTC, davidjwbbc approved these changes
This all looks good, well done Vuk!

2023-09-07 17:14 UTC, rjb1000 commented
I think we're happy to merge this now if you are, @dsilhavy.

2023-09-07 17:33 UTC, dsilhavy commented
> I think we're happy to merge this now if you are, @dsilhavy.

I am still working on some internal approvals. Apologies for the delay, I keep you updated.

2023-10-02 11:49 UTC, stojkovicv commented
Now that TS 26.512 V17.6.0 is available I noticed that `samplingPeriod` field is included within the MetricsReportingConfiguration data model. Therefore, I have to update the code of this PR to the latest specification.

2023-10-04 08:58 UTC, stojkovicv commented
I updated the code to include `samplingPeriod` field for MetricsReportingConfigurations. Good thing is that OpenAPI defitinition was already updated according to the latest TS 26.512, I just had to run bash script once again. I tested all CRUD operations using this mocked data:
```
{
    "scheme": "scheme1",
    "dataNetworkName": "my_network1",
    "isReportingInterval": true,
    "reportingInterval": 60,
    "isSamplePercentage": true,
    "samplePercentage": 0.5,
    "urlFilters": ["filter1", "filter11", "filter111"],
    "samplingPeriod": 2,
    "metrics": ["metric1", "metric11", "metric111"]
}
```
Both `POST` and `GET` are working good, but `UPDATE` and `DELETE` are halting the AF returning this error:
```
Thread 2 "open5gs-msafd" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff4ab0640 (LWP 25502)]
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737298236992) at ./nptl/pthread_kill.c:44
44      ./nptl/pthread_kill.c: No such file or directory.
```
After @davidjwbbc done some changes for this PR, I had trouble with all operations. He instructed to add `no_tls: tru` section in `msaf.yaml`:
```
sbi:
  server:
    no_tls: true
  client:
    no_tls: true
```
This solved the problem for `POST` and `GET` requests. Is it possible to solve errors for remaining requests in the similar manner?

2023-10-19 09:51 UTC, davidjwbbc approved these changes

2023-10-19 09:53 UTC, davidjwbbc commented
This just needs rebasing before pushing to the development branch

2023-10-19 10:57 UTC, davidjwbbc approved these changes

2024-02-05 14:18 UTC, closed without merging